# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-4328-MAC1C79/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      //Mac/Home/Desktop/counter.v
      //Mac/Home/Desktop/vga.v
      {C:/Users/mac/DS LAB/dlab_5/dlab_5.srcs/sources_1/new/Seg7Display.v}
      {C:/Users/mac/DS LAB/dlab_5/dlab_5.srcs/sources_1/new/Multiplexer_4way.v}
      {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/Snake_control.v}
      {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/Target_generator.v}
      //Mac/Home/Desktop/vga_all.v
      {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/Navigation_state_machine.v}
      {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/Master_state_machine.v}
      {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/Score_counter.v}
      {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/Top.v}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top Top
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-4328-MAC1C79/"
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
