# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/mac/DS LAB/snake_game/snake_game.cache/wt} [current_project]
set_property parent.project_path {C:/Users/mac/DS LAB/snake_game/snake_game.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/counter.v}
  {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/vga.v}
  {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/Minus_Counter.v}
  {C:/Users/mac/DS LAB/dlab_5/dlab_5.srcs/sources_1/new/Seg7Display.v}
  {C:/Users/mac/DS LAB/dlab_5/dlab_5.srcs/sources_1/new/Multiplexer_4way.v}
  {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/vga_all.v}
  {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/Target_generator.v}
  {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/Snake_control.v}
  {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/Navigation_state_machine.v}
  {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/Master_state_machine.v}
  {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/Score_counter.v}
  {C:/Users/mac/DS LAB/snake_game/snake_game.srcs/sources_1/new/Top.v}
}
read_xdc {{C:/Users/mac/DS LAB/snake_game/snake_game.srcs/constrs_1/new/snakeXDC.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/mac/DS LAB/snake_game/snake_game.srcs/constrs_1/new/snakeXDC.xdc}}]

synth_design -top Top -part xc7a35tcpg236-1
write_checkpoint -noxdef Top.dcp
catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
